# Generated by Django 4.0.4 on 2022-04-18 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
            },
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.74, -1.39], 'marker_color': 'red'})),
                ('occupants', models.IntegerField(blank=True, default=1)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodx.administrator')),
            ],
            options={
                'verbose_name': 'Neighbourhood',
                'verbose_name_plural': 'Neighbourhoods',
            },
        ),
        migrations.CreateModel(
            name='SocialServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('bank', 'Bank'), ('fire', 'Fire Department'), ('police', 'Police Department'), ('hospital', 'HealthCare'), ('school', 'School')], max_length=30)),
                ('hotline', models.IntegerField()),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.74, -1.39], 'marker_color': 'red'})),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodx.neighbourhood')),
            ],
            options={
                'verbose_name': 'SocialServices',
                'verbose_name_plural': 'SocialServiceses',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodx.neighbourhood')),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-posted'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True, null=True)),
                ('home_location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.74, -1.39], 'marker_color': 'red'})),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodx.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [36.74, -1.39], 'marker_color': 'red'})),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodx.neighbourhood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
