# Generated by Django 4.0.4 on 2022-04-19 06:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1650350714/image/upload/default_cxaayp.jpg', max_length=255, verbose_name='image'),
        ),
    ]
